### ISSUE TITLE
Unable to use the TAB at the same time for completion

### ISSUE THREAD

**Issue by denstiny** [pta2002/intellitab.nvim#1]
I use the coc for completion, the shortcut TAB, when set intelltab will not be able to completion, I hope I can let them work at the same time

I'm sorry my English is poor

**Comment by pta2002** [comment]
Hey, I think I understand what your issue is, I don't use CoC, but I'll set up an install with it so that I can check it out, I think I know how to fix it. Should just require a small change in config.

**Comment by pta2002** [comment]
Okay, I think I know how to solve this, but I'll need to define some sort of .setup method that will set things up so that tab calls intellitab only if it's in the beginning of the line, and calls CoC (or whatever else you had bound to Tab) otherwise. I'll only be able to get this working next week though.

**Comment by denstiny** [comment]
> 好的，我想我知道如何解决这个问题，但是我需要定义某种 .setup 方法来进行设置，以便 tab 仅在行的开头调用 intellitab，并调用 CoC（或其他否则你必须绑定到 Tab) 否则。不过，我只能在下周完成这项工作。


This plugin is a very good, thank you for your help, I'll wait

**Comment by pta2002** [comment]
Hello.

I'm sorry for being gone for so long, but I was away and didn't have time to work on this.

I think I found a way of making the plugin play along with CoC though!

Change these lines from the CoC config

```vim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

to this:

```vim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? <CMD>lua require("intellitab").indent()<CR> :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

Please let me know if this works so I can put it on the README. If it does not I'll figure something else out!

**Comment by denstiny** [comment]
Finally wait for your update, I try at night, thank you remember!
