### ISSUE TITLE
Add cmp mapping Example

### ISSUE THREAD

**Issue by Leiyi548** [pta2002/intellitab.nvim#2]

**Comment by pta2002** [comment]
Hello, is this requesting an example of a mapping for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)?

**Comment by Leiyi548** [comment]
> Hello, is this requesting an example of a mapping for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)?

yes,I need.
thank you

> Hello, is this requesting an example of a mapping for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)?

yes

**Comment by pta2002** [comment]
Hey, can you please try setting up this mapping on nvim-cmp and telling me if it works?

```lua
['<Tab>'] = function(fallback)
  if cmp.visible() then
    cmp.select_next_item() -- or whatever else you want nvim-cmp to do when you press tab
  else
    require("intellitab").indent()
  end
end
```
